Vagrant.configure("2") do |config| 
    config.vm.box = "hashicorp/bionic64"    
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
    end
    config.vm.network "forwarded_port", guest: 6060, host: 6060
end